# See full list at:
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

format_strings = false
imports_granularity = "Crate"
normalize_comments = true
wrap_comments = true

reorder_impl_items = true
use_try_shorthand = true

error_on_line_overflow = true
error_on_unformatted = true

unstable_features = true