[workspace]
members = [
    "ft-token-contract",
    "ft-staking-contract",
    "ft-lockup-contract",
    "nft-token-contract",
]

[profile.release]
codegen-units=1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
