# See full list at:
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

format_strings = false
imports_granularity = "Crate"

reorder_impl_items = true
use_try_shorthand = true

error_on_line_overflow = true
error_on_unformatted = true

unstable_features = true
format_code_in_doc_comments = false
