name: Check Set-Up & Build

on: push

env:
  RUST_BACKTRACE: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Repository Checkout"
      - uses: actions-rs/toolchain@v1
        name: "Rust Toolchain Setup"
        with:
          profile: minimal
          toolchain: stable-x86_64-unknown-linux-gnu
          target: wasm32-unknown-unknown
      - run: cargo build

  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Repository Checkout"
      - uses: actions-rs/toolchain@v1
        name: "Rust Toolchain Setup"
        with:
          profile: minimal
          toolchain: stable-x86_64-unknown-linux-gnu
          target: wasm32-unknown-unknown
      - run: cargo build --release

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Repository Checkout"
      - uses: actions-rs/toolchain@v1
        name: "Rust Toolchain Setup"
        with:
          profile: minimal
          toolchain: stable-x86_64-unknown-linux-gnu
          target: wasm32-unknown-unknown
          components: rustfmt
      - run: cargo fmt

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Repository Checkout"
      - uses: actions-rs/toolchain@v1
        name: "Rust Toolchain Setup"
        with:
          profile: minimal
          toolchain: stable-x86_64-unknown-linux-gnu
          target: wasm32-unknown-unknown
          components: clippy
      - run: cargo clippy

  udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Repository Checkout"
      - uses: actions-rs/toolchain@v1
        name: "Rust Toolchain Setup"
        with:
          profile: minimal
          toolchain: stable-x86_64-unknown-linux-gnu
          target: wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1
        name: "Udeps Installation"
        with:
          command: install
          args: cargo-udeps --locked
      - uses: actions-rs/cargo@v1
        name: "Unused Dependency Check"
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          components: udeps
      - run: cargo +nightly udeps

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Repository Checkout"
      - uses: actions-rs/toolchain@v1
        name: "Rust Toolchain Setup"
        with:
          profile: minimal
          toolchain: stable-x86_64-unknown-linux-gnu
          target: wasm32-unknown-unknown
      - run: cargo test
