name: Udeps
on:
  push:
    paths:
      - '**/Cargo.toml'
jobs:
  udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: install
          args: cargo-udeps --locked
      - run: cargo +nightly udeps